sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
  - sudo apt-get -qq update
  - sudo apt-get install -y bzr lxd build-essential libffi-dev libssl-dev python-dev 

language: python

python:
  - "3.5"


script:
  - bzr branch lp:snappy-ecosystem-tests
  - cd snappy-ecosystem-tests
  - ls -la
  - ./run_setup
